spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##developer
    password: developer
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      leakDetectionThreshold: 2100

filePath: e:\for-developers\onlinefraud.csv

logging:
  level:
    com.zaxxer.hikari: DEBUG